name: potea_plant_e_commerce
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  csv: ^5.1.1
  lottie: ^3.0.0
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  dots_indicator: ^3.0.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/logo.png
    - assets/images/png/welcome_page_image.png
    - assets/username.csv
    - assets/animation/loading.json
    - assets/images/plants/png/Plant01.png
    - assets/images/plants/png/Plant02.png
    - assets/images/plants/png/Plant03.png
    - assets/images/plants/png/Plant04.png
    - assets/images/plants/png/Plant05.png
    - assets/images/plants/png/Plant06.png
    - assets/images/plants/png/Plant07.png
    - assets/images/plants/png/Plant08.png
    - assets/images/plants/png/Plant09.png
    - assets/images/plants/png/Plant10.png
    - assets/images/plants/png/Plant11.png
    - assets/images/plants/png/Plant12.png
    - assets/images/plants/png/Plant13.png
    - assets/images/plants/png/Plant14.png
    - assets/images/plants/png/Plant15.png
    - assets/images/plants/png/Plant16.png
    - assets/images/plants/png/Plant17.png
    - assets/images/plants/png/Plant18.png
    - assets/images/plants/png/Plant19.png
    - assets/images/plants/png/Plant20.png
    - assets/images/plants/png/Plant21.png
    - assets/images/plants/png/Plant22.png
    - assets/images/plants/png/Plant23.png
    - assets/images/plants/png/Plant24.png
    - assets/images/plants/png/Plant25.png
    - assets/images/plants/png/Plant26.png
    - assets/images/plants/png/Plant27.png
    - assets/images/plants/png/Plant28.png
    - assets/images/plants/png/Plant29.png
    - assets/images/plants/png/Plant30.png
    - assets/images/plants/png/Plant31.png
    - assets/images/plants/png/Plant32.png
    - assets/images/plants/png/Plant33.png
    - assets/images/plants/png/Plant34.png
    - assets/images/plants/png/Plant35.png
    - assets/images/plants/png/Plant36.png
    - assets/images/png/loginVector.png
    - assets/images/png/signUpVector.png
    - assets/icons/svg/light(border)/2 User.svg
    - assets/icons/svg/light(border)/3 User.svg
    - assets/icons/svg/light(border)/Activity.svg
    - assets/icons/svg/light(border)/Add User.svg
    - assets/icons/svg/light(border)/Arrow - Down.svg
    - assets/icons/svg/light(border)/Arrow - Down Circle.svg
    - assets/icons/svg/light(border)/Arrow - Down Square.svg
    - assets/icons/svg/light(border)/Arrow - Down 2.svg
    - assets/icons/svg/light(border)/Arrow - Down 3.svg
    - assets/icons/svg/light(border)/Arrow - Left.svg
    - assets/icons/svg/light(border)/Arrow - Left Circle.svg
    - assets/icons/svg/light(border)/Arrow - Left Square.svg
    - assets/icons/svg/light(border)/Arrow - Left 2.svg
    - assets/icons/svg/light(border)/Arrow - Left 3.svg
    - assets/icons/svg/light(border)/Arrow - Right.svg
    - assets/icons/svg/light(border)/Arrow - Right Circle.svg
    - assets/icons/svg/light(border)/Arrow - Right Square.svg
    - assets/icons/svg/light(border)/Arrow - Right 2.svg
    - assets/icons/svg/light(border)/Arrow - Right 3.svg
    - assets/icons/svg/light(border)/Arrow - Up.svg
    - assets/icons/svg/light(border)/Arrow - Up Circle.svg
    - assets/icons/svg/light(border)/Arrow - Up Square.svg
    - assets/icons/svg/light(border)/Arrow - Up 2.svg
    - assets/icons/svg/light(border)/Arrow - Up 3.svg
    - assets/icons/svg/light(border)/Bag.svg
    - assets/icons/svg/light(border)/Bag 3.svg
    - assets/icons/svg/light(border)/Bookmark.svg
    - assets/icons/svg/light(border)/Buy.svg
    - assets/icons/svg/light(border)/Calendar.svg
    - assets/icons/svg/light(border)/Call.svg
    - assets/icons/svg/light(border)/Call Missed.svg
    - assets/icons/svg/light(border)/Call Silent.svg
    - assets/icons/svg/light(border)/Calling.svg
    - assets/icons/svg/light(border)/Camera.svg
    - assets/icons/svg/light(border)/Category.svg
    - assets/icons/svg/light(border)/Chart.svg
    - assets/icons/svg/light(border)/Chat.svg
    - assets/icons/svg/light(border)/Close Square.svg
    - assets/icons/svg/light(border)/Danger Circle.svg
    - assets/icons/svg/light(border)/Danger Triangle.svg
    - assets/icons/svg/light(border)/Delete.svg
    - assets/icons/svg/light(border)/Discount.svg
    - assets/icons/svg/light(border)/Discovery.svg
    - assets/icons/svg/light(border)/Document.svg
    - assets/icons/svg/light(border)/Download.svg
    - assets/icons/svg/light(border)/Edit.svg
    - assets/icons/svg/light(border)/Edit Square.svg
    - assets/icons/svg/light(border)/Filter.svg
    - assets/icons/svg/light(border)/Filter 3.svg
    - assets/icons/svg/light(border)/Folder.svg
    - assets/icons/svg/light(border)/Game.svg
    - assets/icons/svg/light(border)/Graph.svg
    - assets/icons/svg/light(border)/Heart.svg
    - assets/icons/svg/light(border)/hide.svg
    - assets/icons/svg/light(border)/Home.svg
    - assets/icons/svg/light(border)/Image.svg
    - assets/icons/svg/light(border)/Image 3.svg
    - assets/icons/svg/light(border)/Info Square.svg
    - assets/icons/svg/light(border)/Location.svg
    - assets/icons/svg/light(border)/lock.svg
    - assets/icons/svg/light(border)/Login.svg
    - assets/icons/svg/light(border)/Logout.svg
    - assets/icons/svg/light(border)/message.svg
    - assets/icons/svg/light(border)/More Circle.svg
    - assets/icons/svg/light(border)/More Square.svg
    - assets/icons/svg/light(border)/Notification.svg
    - assets/icons/svg/light(border)/Paper.svg
    - assets/icons/svg/light(border)/Paper Download.svg
    - assets/icons/svg/light(border)/Paper Fail.svg
    - assets/icons/svg/light(border)/Paper Negative.svg
    - assets/icons/svg/light(border)/Paper Plus.svg
    - assets/icons/svg/light(border)/Paper Upload.svg
    - assets/icons/svg/light(border)/Password.svg
    - assets/icons/svg/light(border)/Play.svg
    - assets/icons/svg/light(border)/Plus.svg
    - assets/icons/svg/light(border)/Profile.svg
    - assets/icons/svg/light(border)/Scan.svg
    - assets/icons/svg/light(border)/Search.svg
    - assets/icons/svg/light(border)/Send.svg
    - assets/icons/svg/light(border)/Setting.svg
    - assets/icons/svg/light(border)/Shield Done.svg
    - assets/icons/svg/light(border)/Shield Fail.svg
    - assets/icons/svg/light(border)/Show.svg
    - assets/icons/svg/light(border)/Star.svg
    - assets/icons/svg/light(border)/Swap.svg
    - assets/icons/svg/light(border)/Tick Square.svg
    - assets/icons/svg/light(border)/Ticket.svg
    - assets/icons/svg/light(border)/Ticket Star.svg
    - assets/icons/svg/light(border)/Time Circle.svg
    - assets/icons/svg/light(border)/Time Square.svg
    - assets/icons/svg/light(border)/Unlock.svg
    - assets/icons/svg/light(border)/Upload.svg
    - assets/icons/svg/light(border)/Video.svg
    - assets/icons/svg/light(border)/Voice.svg
    - assets/icons/svg/light(border)/Voice 3.svg
    - assets/icons/svg/light(border)/Volume Down.svg
    - assets/icons/svg/light(border)/Volume Off.svg
    - assets/icons/svg/light(border)/Volume Up.svg
    - assets/icons/svg/light(border)/Wallet.svg
    - assets/icons/svg/light(border)/Work.svg
    - assets/icons/svg/vector/apple.svg
    - assets/icons/svg/vector/google.svg
    - assets/icons/svg/vector/facebook.svg
    - assets/icons/svg/boldIcon/hideIcon.svg
    - assets/icons/svg/boldIcon/lockIcon.svg
    - assets/icons/svg/boldIcon/messageIcon.svg

  fonts:
    - family: urbanistRegular
      fonts:
        - asset: assets/fonts/en/Urbanist-Regular.ttf
    - family: urbanistMedium
      fonts:
        - asset: assets/fonts/en/Urbanist-Medium.ttf
    - family: urbanistSemiBold
      fonts:
        - asset: assets/fonts/en/Urbanist-SemiBold.ttf
    - family: urbanistBold
      fonts:
        - asset: assets/fonts/en/Urbanist-Bold.ttf
    - family: iranYekanRegular
      fonts:
        - asset: assets/fonts/fa/iranYekanRegular.ttf
    - family: iranYekanBold
      fonts:
        - asset: assets/fonts/fa/iranYekanBold.ttf
