name: potea_plant_e_commerce
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  csv: ^5.1.1
  lottie: ^3.0.0
  cupertino_icons: ^1.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/png/logo.png
    - assets/images/png/welcome_page_image.png
    - assets/username.csv


  fonts:
    - family: urbanistRegular
      fonts:
        - asset: assets/fonts/en/Urbanist-Regular.ttf
    - family: urbanistMedium
      fonts:
        - asset: assets/fonts/en/Urbanist-Medium.ttf
    - family: urbanistSemiBold
      fonts:
        - asset: assets/fonts/en/Urbanist-SemiBold.ttf
    - family: urbanistBold
      fonts:
        - asset: assets/fonts/en/Urbanist-Bold.ttf
    - family: iranYekanRegular
      fonts:
        - asset: assets/fonts/fa/iranYekanRegular.ttf
    - family: iranYekanBold
      fonts:
        - asset: assets/fonts/fa/iranYekanBold.ttf
